name: cyrustourist_app3
description: CyrusTourist base app - splash, home and tourist map.
publish_to: "none"

version: 5.7.1+5710

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.jpg
    - assets/images/home.jpg
    - assets/images/logo-new.jpg
